### ISSUE TITLE
Workflow

### ISSUE THREAD

**Issue by sa-lee** [nullranges/nullranges#2]
*  invoke a generator that explains how you want to generate a null set (see #1)
* "sample" from the null based on your ranges object and the generator
* "diagnose" the null set, what would this involve?
* "summarise" or collapse the null set to generate summary stats via plyranges or through regular GenomicRanges

Would you want to plot a null set too?

**Comment by mikelove** [comment]
A diagram from a meeting with Wancen.

We are realizing that for the bootstrap analysis, we will have a nullranges sandwich. 

Above, we "sample" potentially multiple sets of bootstrap ranges, indexed by `L_b` the block length. So this is multiple levels of nesting: block length (grid of say, 3-5 options), bootstrap (R = ~100-200), then the ranges themselves.

Then the user will do some plyranges analysis, e.g. compute overlaps of genes and peaks (original and bootstrap). We should consider that this step is easy to parallel, does plyranges have support for this? Thoughts?

Finally, the user returns to nullranges in order to determine the optimal block length (the "diagnose" step you outline above). We have two plots that help guide this choice.

Finally, they may want to "summarise": e.g. how far the observed overlap is from the bootstrap distribution (now they've picked a single `L_b` so they just have one bootstrap distribution to consider).

![Screen Shot 2021-05-03 at 3 03 55 PM](https://user-images.githubusercontent.com/69203/116921406-f341b500-ac21-11eb-964a-b35da2b28065.png)

**Comment by sa-lee** [comment]
That sounds really good. I think the overlaps ops could be done in parallel with existing Bioconductor infrastructure with then plyranges functions, as I'm not sure exactly what you have in mind here.

**Comment by mikelove** [comment]
The overlaps ops will be, for each choice of L_b and each bootstrap iteration, e.g.:

- calculate the mean number overlaps of genes to the bootstrap peak ranges

There could be more complex statistics calculated in this step (e.g. maybe the mean and SD of number of overlaps, or other distribution aspects), but this is the simplest I think.
