### ISSUE TITLE
Combining matchRanges with bootRanges

### ISSUE THREAD

**Issue by Jome0169** [nullranges/nullranges#26]
Hello,

I was wondering if it's possible to use bootRanges in tandem with matchRanges in order to produced a bootstrapped set of intervals which match to a covariate? Based off the documentation I can't find if there is currently an easy way of doing this.

Thanks for any input or guidance you might provide.

**Comment by mikelove** [comment]
Let me just make sure I have it correct. 

You have a set `x` that is fixed, and you have a `pool` from which you would like to draw a set `y` that matches on some covariates with `x`.

But then you additionally want to permute the locations of `y` through bootstrapping?

**Comment by Jome0169** [comment]
Almost. I don't want to permute the locations of `y`, rather I would like 5,000 samples of different `y`'s all matched to the covariate from `x`. And as you mentioned `x` and `pool` are fixed. Thank you for your prompt response.

**Comment by mikelove** [comment]
You can just run `matchRanges` again, e.g. from the vignette

```
## Match ranges
set.seed(123)
mgr <- matchRanges(focal = bins[bins$looped],
                   pool = bins[!bins$looped],
                   covar = ~dnaseSignal + n_dnase_sites)
```

Here, because the seed was set, we get the same ranges again if we run those two lines of code. But if you set the seed and then run matchRanges 100 times, you will get 100 different subsets.

A couple of notes:

1. you want to set the seed still, but just once, and then not again in between the subsequent runs.
2. you can keep track of the runs by calling matchRanges within an lapply (you can then bind them together with bind_ranges)
3. you will need to inspect the ranges afterward for overlap. it can be that there is only a small number of ranges in the pool that offer covariate matching. in the extreme, you could end up with the same set of ranges 100 times

@EricSDavis it may be worth putting some information about this at the bottom of the main matchRanges vignette, maybe also in the man page

**Comment by Jome0169** [comment]
Got it. That is my current approach. I guess I was trying to see if there were inbuilt functions in nullRanges I wasn't aware of to do this. Thank you for the additional clarity. I'll go ahead and close this issue.
